# Site settings
title: KurTakon
email: kikicandra@kurtakon.com
description: > # this means to ignore newlines until "baseurl:"
  Quote : <br>
  Takonlah sebelum takon itu dilarang.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kurtakon.com" # the base hostname & protocol for your site
urlimg: "https://kurtakon.com/asset/img/" # the base hostname & protocol for your site
##urlimg: "http://127.0.0.1:4000/asset/img/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

include: ['.htaccess']
# Google services
google_analytics: UA-104179765-1

permalink: pretty

plugins: [jekyll-paginate] 
paginate: 3
paginate_path: /page:num/