# Site settings
title: KurTakon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  .... KurTakon ... 
  Takonlah sebelum takon itu dilarang...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kurtakon.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
